name: Github CI

on:
  push:
    branches:
      - main
      - v8.21
      - v8.20
      - v8.19
      - v8.18
      - v8.17
      - v8.16
      - v8.15
  pull_request:
    branches:
      - main
      - v8.21
      - v8.20
      - v8.19
      - v8.18
      - v8.17
      - v8.16
      - v8.15

# Cancels previous runs of the same workflow
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Windows Latest
            ocaml: 4.14.x
            os: windows-latest
      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 45

    steps:
      - name: 🔭 Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 🐫 Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml }}
          dune-cache: true

      - name: 🐫🐪🐫 Get dependencies
        run: |
          opam pin add --dev dune
          opam pin add --dev ocamlfind
          opam exec -- make opam-deps

      - name: 🐛 Special Windows Config [only on Win CI]
        if: matrix.os == 'windows-latest'
        run: opam exec -- make winconfig

      - name: 🧱 Build coq-lsp
        run: opam exec -- make build

      - name: 🐛 Test coq-lsp
        run: opam exec -- make test

      - name: 🐛 Test fcc
        run: opam exec -- make test-compiler
